name: 'Smoke test'
description: 'Smoke test'
inputs:
  template:
    description: 'Template to test'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@main

    - name: Build template
      id: build_template
      shell: bash
      run: ${{ github.action_path }}/build.sh ${{ inputs.template }}

    - name: Test template
      id: test_template
      shell: bash
      run: ${{ github.action_path }}/test.sh  ${{ inputs.template }}