name: "Build hugo versions"
env:
  NAME: hugo
on:
  push:
    paths:
      - src/hugo/**
      - .github/workflows/hugo.yaml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        imageVariant:
          ["stretch", "buster", "bullseye", "bookworm", "stable", "testing"]
        hugoVersion: ["latest", "0.108.0", "0.107.0", "0.106.0", "0.105.0"]
        extended: [true, false]
    name: Build ${{ matrix.imageVariant }}-${{ matrix.hugoVersion }} (Extended:${{ matrix.extended }})
    steps:
      - uses: actions/checkout@main

      - name: Generate devcontainer-template.json
        shell: bash
        run: |
          cp -v -r src/${{ env.NAME }} /tmp/
          cp -v .github/actions/utils/* /tmp/${{ env.NAME }}/
          cd /tmp/${{ env.NAME }}
          python generate-template.py ${{ matrix.imageVariant }} ${{ matrix.hugoVersion }} ${{ matrix.extended }}
          echo "Content of devcontainer-template.json"
          cat devcontainer-template.json
          bash apply-template.sh
          echo "Content of devcontainer.json"
          cat .devcontainer/devcontainer.json

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build and push
        if: ${{ matrix.extended == false }}
        env:
          DOCKER_BUILDKIT: 1
        run: |
          npm install -g @devcontainers/cli
          cd /tmp/${{ env.NAME }}
          devcontainer build --image-name ${{ env.NAME }} --workspace-folder .
          docker tag ${{ env.NAME }} ${{ github.repository_owner }}/devcontainer-images:${{ env.NAME }}-${{ matrix.imageVariant }}-${{ matrix.hugoVersion }}
          docker tag ${{ env.NAME }} ghcr.io/${{ github.repository_owner }}/devcontainer-images:${{ env.NAME }}-${{ matrix.imageVariant }}-${{ matrix.hugoVersion }}
          docker tag ${{ env.NAME }} ${{ github.repository_owner }}/devcontainer-${{ env.NAME }}:${{ matrix.imageVariant }}-${{ matrix.hugoVersion }}
          docker tag ${{ env.NAME }} ghcr.io/${{ github.repository_owner }}/devcontainer-${{ env.NAME }}:${{ matrix.imageVariant }}-${{ matrix.hugoVersion }}
          docker push --all-tags ${{ github.repository_owner }}/devcontainer-images
          docker push --all-tags ghcr.io/${{ github.repository_owner }}/devcontainer-images
          docker push --all-tags ${{ github.repository_owner }}/devcontainer-${{ env.NAME }}
          docker push --all-tags ghcr.io/${{ github.repository_owner }}/devcontainer-${{ env.NAME }}

      - name: Build and push extended
        if: ${{ matrix.extended }}
        env:
          DOCKER_BUILDKIT: 1
        run: |
          npm install -g @devcontainers/cli
          cd /tmp/${{ env.NAME }}
          devcontainer build --image-name ${{ env.NAME }} --workspace-folder .
          docker tag ${{ env.NAME }} ${{ github.repository_owner }}/devcontainer-images:${{ env.NAME }}-${{ matrix.imageVariant }}-${{ matrix.hugoVersion }}-extened
          docker tag ${{ env.NAME }} ghcr.io/${{ github.repository_owner }}/devcontainer-images:${{ env.NAME }}-${{ matrix.imageVariant }}-${{ matrix.hugoVersion }}-extened
          docker tag ${{ env.NAME }} ${{ github.repository_owner }}/devcontainer-${{ env.NAME }}:${{ matrix.imageVariant }}-${{ matrix.hugoVersion }}-extened
          docker tag ${{ env.NAME }} ghcr.io/${{ github.repository_owner }}/devcontainer-${{ env.NAME }}:${{ matrix.imageVariant }}-${{ matrix.hugoVersion }}-extened
          docker push --all-tags ${{ github.repository_owner }}/devcontainer-images
          docker push --all-tags ghcr.io/${{ github.repository_owner }}/devcontainer-images
          docker push --all-tags ${{ github.repository_owner }}/devcontainer-${{ env.NAME }}
          docker push --all-tags ghcr.io/${{ github.repository_owner }}/devcontainer-${{ env.NAME }}

  finishing:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Delete untagged
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: devcontainer-${{ env.NAME }}
          token: ${{ secrets.PAT }}
          user: ${{ github.repository_owner }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/devcontainer-${{ env.NAME }}
          short-description: "Dev Container hugo built with templates"
          readme-filepath: src/${{ env.NAME }}/README.md
