name: "CI - Test Templates"
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - test/**
  pull_request:
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@main
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            hugo: ./**/hugo/**
            latex: ./**/latex/**
            python: ./**/python/**

  test:
    needs: detect-changes
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
    steps:
      - uses: actions/checkout@main

      - name: Smoke test for '${{ matrix.templates }}'
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"
